name: Tests


on:
  workflow_dispatch:
    inputs:
      bool:
        type: boolean
        required: true
        description: ""

jobs:
  call:
    uses: mnicolas94/github-actions-tests/.github/workflows/workflow_call_tests.yml@main
    with:
      bool: ${{ inputs.bool }}
      str: "asdqw"
    secrets: inherit
