name: Tests


on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      foo:
        type: choice
        default: 'dev'
        options:
          - dev
          - stag
          - prod

jobs:
  call:
    name: test 1
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ inputs.foo }}
      - if: ${{ inputs.foo == '' || inputs.foo == 'dev' }}
        run: |
          echo is dev
          echo ${{ github.ref }}
        
      
  
