name: Tests


on:
  workflow_dispatch:
    inputs:
      bool:
        type: boolean
        required: true
        description: ""

jobs:
  call:
    uses: mnicolas94/github-actions-tests/.github/workflows/workflow_call_tests.yml@main
    with:
      bool: ${{ inputs.bool }}
      str: "asdqw"
    secrets:
      SECRET_A: ${{ secrets.SECRET_A }}
      SECRET_B: ${{ secrets.SECRET_B }}
      SOME_SECRET: ${{ secrets.SOME_SECRET }}
