name: Tests


on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      foo:
        type: choice
        default: 'dev'
        options:
          - dev
          - stag
          - prod

jobs:
  call:
    name: test 1
    runs-on: ubuntu-latest
    env:
      foo: ${{ inputs.foo || 'asdqwezxc' }}
    steps:
      - run: |
          echo ${{ inputs.foo }}
          echo ${{ env.foo }}
