name: Tests


on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      foo:
        type: boolean
        default: false

jobs:
  call:
    name: test 1
    runs-on: ${{ fromJSON('["macos-latest", "ubuntu-latest"]')[inputs.foo] }}
    steps:
      - run: |
          echo ${{ inputs.foo }}
          echo ${{ runner.os }}
