name: Tests


on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      foo:
        type: choice
        default: 'dev'
        options:
          - dev
          - stag
          - prod

jobs:
  call:
    name: test 1
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ inputs.foo }}
      - if: ${{ inputs.foo == '' || inputs.foo == 'dev' }}
        run: |
          exit 1
          
  fail:
    name: fail
    runs-on: ubuntu-latest
    steps:
      - run: |
          exit 1
  
  call2:
    name: test 2
    needs: [call, fail]
    if: ${{ always() && needs.call.result == 'success' && needs.fail.result == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ needs.call.result }}
  
