name: Tests


on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      foo:
        type: string
        default: "iOS"

jobs:
  call:
    name: test 1
    runs-on: ${{ fromJSON('["ubuntu-latest", "macos-latest"]')[inputs.foo == 'iOS'] }}
    steps:
      - run: |
          echo ${{ inputs.foo }}
          echo ${{ runner.os }}
