name: Workflow call tests

on:
  workflow_call:
    inputs:
      bool:
        type: boolean
        required: true
      str:
        type: string
        required: true
      

jobs:
  job1:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: r
        run: |
          echo ${{ inputs.bool }}
          echo ${{ inputs.str }}
          echo ${{ secrets.SOME_SECRET }}
          echo ${{ secrets.SECRET_A }}
          echo ${{ secrets.SECRET_B }}
      - name: echo secret a
        uses: mnicolas94/github-actions-tests@main
        with:
          foo: ${{ secrets.SECRET_A }}
      
