name: Workflow call tests

on:
  workflow_call:
    inputs:
      bool:
        type: boolean
        required: true
      str:
        type: string
        required: true
    secrets:
      SECRET_A:
        required: true
      SECRET_B:
        required: true
      SOME_SECRET:
        required: true
      

jobs:
  job1:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: r
        run: |
          echo ${{ inputs.bool }}
          echo ${{ inputs.str }}
          echo ${{ secrets.SOME_SECRET }}
      - name: a
        if: ${{ secrets.SECRET_A == 'a' }}
        run: |
          echo "secretA is a"
      - name: b
        if: ${{ secrets.SECRET_B == 'b' }}
        run: |
          echo "secretB is b"
          
      
